// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASTgFphULVw35mvIHDu6pcy_uLKQ3s0Zs',
    appId: '1:372094160885:web:9ae1e967c383da71ee9abc',
    messagingSenderId: '372094160885',
    projectId: 'problock-e9c16',
    authDomain: 'problock-e9c16.firebaseapp.com',
    storageBucket: 'problock-e9c16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0xW2Gklxrzl4qpU8Mn3zIh0GM9VT2tKk',
    appId: '1:372094160885:android:7d719fdf890b7bd0ee9abc',
    messagingSenderId: '372094160885',
    projectId: 'problock-e9c16',
    storageBucket: 'problock-e9c16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG7_RKLylyS32htE-o1ucf7bUkn7v2ZoA',
    appId: '1:372094160885:ios:309205ecc4db4d68ee9abc',
    messagingSenderId: '372094160885',
    projectId: 'problock-e9c16',
    storageBucket: 'problock-e9c16.appspot.com',
    iosClientId: '372094160885-54iaetoqbdvi45hnss3qudoim864phgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.problock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG7_RKLylyS32htE-o1ucf7bUkn7v2ZoA',
    appId: '1:372094160885:ios:309205ecc4db4d68ee9abc',
    messagingSenderId: '372094160885',
    projectId: 'problock-e9c16',
    storageBucket: 'problock-e9c16.appspot.com',
    iosClientId: '372094160885-54iaetoqbdvi45hnss3qudoim864phgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.problock',
  );
}
